[tool.poetry]
name = "csp_ii"
version = "0.1.0"
description = ""
authors = ["Tom Kunc <tomkunc0@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
z3-solver = "^4.8.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
